### ISSUE TITLE
Missing type validation

### ISSUE THREAD

**Issue by francisbergin** [containers/podman-py#292] opened 2023-06-18 15:09 UTC
Although type hints are used throughout the package, there doesn't seem to be any type validation being done.

Running mypy for the podman package currently returns quite a few type errors:

```console
$ mypy --package podman
...
Found 152 errors in 22 files (checked 74 source files)
```

The number of errors will be bigger or smaller depending on the mypy config that is used. Also, specific lines/modules can be ignored if they shouldn't be checked. Lastly, perhaps mypy is not the type checking tool that is to be used.

**Comment by umohnani8** [comment] 2024-01-23 13:02
Duplicate of https://github.com/containers/podman-py/issues/293, closing in favor of that one.

**Closed by umohnani8** 2024-01-23 13:02 UTC
