### ISSUE TITLE
Where are the docs published?

### ISSUE THREAD

**Issue by cjw296** [containers/podman-py#246] opened 2023-02-28 08:39 UTC
I see Sphinx source in the repo, but where is it published?

**Comment by zentialEdwardSu** [comment] 2023-03-25 10:25
I guess the site is not ready yet, It seems `make docs` is the only way we can see the docs XD

**Comment by jwhonce** [comment] 2023-04-11 16:22
Duplicate of https://github.com/containers/podman-py/issues/101

**Closed** 2023-04-11 16:22 UTC
Labels: duplicate
